version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 40s

  backend:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=user1
      - DB_PASS=password1
      - DB_NAME=mydatabase
      - JWT_SECRET_KEY=yourSuperSecretKey
    depends_on:
      mysql:
        condition: service_healthy

  vue-app:
    build:
      context: ../frontend
      dockerfile: DockerFile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db-data:
